use_frameworks!

target 'KWTextStyleLabel_Example' do
  pod 'KWTextStyleLabel', :path => '../'

  target 'KWTextStyleLabel_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
